{
 "title": "OpenTelemetry",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "OpenTelemetry Collector Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Startup",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 1 },
   "targets": [
    { "expr": "target_info{}", "legendFormat": "{{service_version}}" }
   ]
  },
  { "title": "Traces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Receiver Accepted Spans",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "otelcol_receiver_accepted_spans{}",
     "legendFormat": "{{instance}} | {{ transport }}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "targets": [
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Receiver Dropped Spans",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "otelcol_receiver_refused_spans{}",
     "legendFormat": "{{instance}} | {{transport}}"
    }
   ]
  },
  {
   "title": "Processor Accepted Spans",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "otelcol_processor_accepted_spans{}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Processor Refused Spans",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "otelcol_processor_refused_spans{}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Processor Dropped Spans",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "otelcol_processor_dropped_spans{}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Processor Batch Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "otelcol_processor_batch_batch_send_size_count{}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Exporter Sent Spans",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
   "targets": [
    { "expr": "otelcol_exporter_sent_spans{}", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Exporter Send Failed Spans",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 26 },
   "targets": [
    {
     "expr": "otelcol_exporter_send_failed_spans{}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}